database:
  type: YAML # YAML or MONGODB
  mongo:
    uri: "mongodb://localhost"
config:
  auto-save:
    enabled: true
    seconds: 900
  command-on-support:
    enabled: true
    command-to-execute: "give %name% diamond 32"
  stop-supporting: false
  max-supports-per-player: 1
